version: '3'
services:

  grafana-agent:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: grafana/agent:latest
    volumes:
      - ./data/agent:/etc/agent/data
      - ./agent.yml:/etc/agent/agent.yaml
    ports:
      - "12345:12345"

  ficsit-agent:
    build: .
    command: -scrape-interval=10s -frm-url="http://host.docker.internal:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1234:1234"